version: '3'
services:
  api:
    container_name: indicators
    build:
      context: ../indicators-api
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - app-network
  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx.dockerfile
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
